spring:
  application:
    name: servico-combate

  profiles:
    active: postgres

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8083}

services:
  character-service:
    url: http://localhost:8081
