spring:
  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.egnbgiknsyzojqfddxyt&password=bOABJ5b2iswaud8L
    username: postgres.egnbgiknsyzojqfddxyt
    password: bOABJ5b2iswaud8L

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
