spring:
  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.egnbgiknsyzojqfddxyt&password=rgHQOoMd8ggky7Ut
    username: postgres.egnbgiknsyzojqfddxyt
    password: rgHQOoMd8ggky7Ut

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
