plugins {
    id 'groovy'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {

    // LITIENGINE
    implementation 'de.gurkenlabs:litiengine:0.5.2'

    // GROOVY
    implementation 'org.codehaus.groovy:groovy-all:3.0.21'

    // MP3 PLAYER
    implementation 'javazoom:jlayer:1.0.1'
}

application {

    mainClass = 'game.Main'
}